package es.uvigo.esei.tfg.dao.recipe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import es.uvigo.esei.tfg.dao.DAO;
import es.uvigo.esei.tfg.entities.recipe.Recipe;
import es.uvigo.esei.tfg.entities.recipe.RecipeStep;
import es.uvigo.esei.tfg.exceptions.DAOException;

/**
 * DAO class for managing {@link RecipeStep} entities in the database.
 */
public class RecipeStepDAO extends DAO {
    private final static Logger LOG = Logger.getLogger(RecipeStepDAO.class.getName());

    //============     CREATE     ============

    public RecipeStep create(RecipeStep recipeStep)
    throws DAOException, IllegalArgumentException {
        return create(recipeStep, null);
    }

    /**
     * Persists a new {@link RecipeStep} entity in the database.
     * The ID of the step will be automatically generated by the database and set in the returned entity.
     * 
     * @param step the recipe step to be created. Must not be null and must have a valid associated recipe.
     * @return the created recipe step with the generated ID.
     * @throws DAOException if there is an error during the database operation.
     * @throws IllegalArgumentException if the provided step is null or has invalid data.
     */
    public RecipeStep create(RecipeStep step, Connection externalConnection) 
    throws DAOException, IllegalArgumentException {
        ensureRecipeStepDataIntegrity(step);

        boolean isExternalConnection = isExternalConnection(externalConnection);
        Connection conn = null;

        try {
            conn = this.getConnection(externalConnection);

            final String query = "INSERT INTO recipe_steps" +
                " (step_number, title, description, image_path, recipe_id)" +
                " VALUES (?, ?, ?, ?, ?)";

            try (final PreparedStatement statement = conn.prepareStatement(query, PreparedStatement.RETURN_GENERATED_KEYS)) {
                statement.setInt(1, step.getStepNumber());
                statement.setString(2, step.getTitle());
                statement.setString(3, step.getDescription());
                statement.setString(4, step.getImagePath());
                
                statement.setLong(5, step.getRecipe().getId());

                int affectedRows = statement.executeUpdate();
                if (affectedRows == 0) {
                    throw new DAOException("Creating recipe step failed, no rows affected.");
                }

                try (final ResultSet generatedKeys = statement.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        step.setId(generatedKeys.getLong(1));
                        return step;
                    } else {
                        throw new DAOException("Creating recipe step failed, no ID obtained.");
                    }
                }
            }
        } catch (SQLException e) {
            LOG.log(Level.SEVERE, "Error creating a recipe step", e);
            throw new DAOException(e);
        } finally {
            closeConnection(conn, isExternalConnection);
        }
    }

    /**
     * Persists a list of {@link RecipeStep} entities in the database.
     * All steps must be associated with the same valid recipe.
     * 
     * @param steps the list of recipe steps to be created. Must not be null or empty.
     * @throws DAOException if there is an error during the database operation.
     * @throws IllegalArgumentException if the provided list is null, empty, or contains invalid steps.
     */
    public List<RecipeStep> createAll(List<RecipeStep> steps, Connection externalConnection) 
    throws DAOException, IllegalArgumentException {
        if (steps == null || steps.isEmpty()) {
            throw new IllegalArgumentException("Recipe steps list cannot be null or empty");
        }

        List<RecipeStep> createdSteps = new LinkedList<>();
        for (RecipeStep step: steps) {
            createdSteps.add(create(step, externalConnection));
        }
        return createdSteps;
    }

    //============     READ     ============

    /**
     * Retrieves a {@link RecipeStep} entity from the database by its ID.
     * 
     * @param id the identifier of the recipe step to retrieve.
     * @return the recipe step with the specified ID.
     * @throws DAOException if there is an error during the database operation.
     * @throws IllegalArgumentException if no recipe step is found with the given ID.
     */
    public RecipeStep get(long id)
    throws DAOException, IllegalArgumentException {
        try (final Connection conn = this.getConnection(null)) {
            final String query = "SELECT * FROM recipe_steps WHERE id_recipe_step=?";

            try (final PreparedStatement statement = conn.prepareStatement(query)) {
                statement.setLong(1, id);

                try (final ResultSet result = statement.executeQuery()) {
                    if (result.next()) {
                        return rowToEntity(result);
                    } else {
                        throw new IllegalArgumentException("No recipe step found with ID: " + id);
                    }
                }
            }
        } catch (SQLException e) {
            LOG.log(Level.SEVERE, "Error retrieving a recipe step by ID", e);
            throw new DAOException(e);
        }
    }

    /**
     * Retrieves all {@link RecipeStep} entities associated with a specific recipe ID.
     * The steps are ordered by their step number in ascending order.
     * 
     * @param recipeId the identifier of the recipe whose steps are to be retrieved.
     * @return a list of recipe steps associated with the specified recipe ID.
     * @throws DAOException if there is an error during the database operation.
     * @throws IllegalArgumentException if no steps are found for the given recipe ID.
     */
    public List<RecipeStep> getByRecipeId(long recipeId) 
    throws DAOException, IllegalArgumentException {
        try (final Connection conn = this.getConnection(null)) {
            final String query = "SELECT * FROM recipe_steps WHERE recipe_id=?" + 
                " ORDER BY step_number ASC";

            try (final PreparedStatement statement = conn.prepareStatement(query)) {
                statement.setLong(1, recipeId);

                try (final ResultSet result = statement.executeQuery()) {
                    List<RecipeStep> steps = new LinkedList<>();
                    while (result.next()) {
                        steps.add(rowToEntity(result));
                    }
                    return steps;
                }
            }
        } catch (SQLException e) {
            LOG.log(Level.SEVERE, "Error retrieving recipe steps by recipe ID", e);
            throw new DAOException(e);
        }
    }

    //============     UPDATE     ============

    /**
     * Updates an existing {@link RecipeStep} entity in the database.
     * The step to be updated is identified by the ID field of the provided entity.
     * 
     * @param step the recipe step with updated data. Must not be null and must have a valid ID and associated recipe.
     * @throws DAOException if there is an error during the database operation.
     * @throws IllegalArgumentException if the provided step is null, has invalid data, or no existing step is found with the given ID.
     */
    public void update(RecipeStep step)
    throws DAOException, IllegalArgumentException {
        ensureRecipeStepDataIntegrity(step);

        try (final Connection conn = this.getConnection(null)) {
            final String query = "UPDATE recipe_steps SET" +
                " step_number=?, title=?, description=?, image_path=?" +
                " WHERE id_recipe_step=?";

            try (final PreparedStatement statement = conn.prepareStatement(query)) {
                statement.setInt(1, step.getStepNumber());
                statement.setString(2, step.getTitle());
                statement.setString(3, step.getDescription());
                statement.setString(4, step.getImagePath());
                statement.setLong(5, step.getId());

                int affectedRows = statement.executeUpdate();
                if (affectedRows == 0) {
                    throw new IllegalArgumentException("No recipe step found with ID: " + step.getId());
                }
            }
        } catch (SQLException e) {
            LOG.log(Level.SEVERE, "Error updating a recipe step", e);
            throw new DAOException(e);
        }
    }

    //============     DELETE     ============

    /**
     * Deletes a {@link RecipeStep} entity from the database by its ID.
     * 
     * @param id the identifier of the recipe step to delete.
     * @throws DAOException if there is an error during the database operation.
     * @throws IllegalArgumentException if no recipe step is found with the given ID.
     */
    public void delete(long id) 
    throws DAOException, IllegalArgumentException {
        try (final Connection conn = this.getConnection(null)) {
            final String query = "DELETE FROM recipe_steps WHERE id_recipe_step=?";

            try (final PreparedStatement statement = conn.prepareStatement(query)) {
                statement.setLong(1, id);

                if (statement.executeUpdate() == 0) {
                    throw new IllegalArgumentException("No recipe step found with ID: " + id);
                }
            }
        } catch (SQLException e) {
            LOG.log(Level.SEVERE, "Error deleting a recipe step", e);
            throw new DAOException(e);
        }
    }

    public void deleteByRecipeId(long recipeId)
    throws DAOException, IllegalArgumentException {
        deleteByRecipeId(recipeId, null);
    }

    /**
     * Deletes all {@link RecipeStep} entities associated with a specific recipe ID.
     * 
     * @param recipeId the identifier of the recipe whose steps are to be deleted.
     * @throws DAOException if there is an error during the database operation.
     * @throws IllegalArgumentException if no steps are found for the given recipe ID.
     */
    public void deleteByRecipeId(long recipeId, Connection externalConnection)
    throws DAOException, IllegalArgumentException {
        boolean isExternalConnection = isExternalConnection(externalConnection);
        Connection conn = null;

        try {
            conn = this.getConnection(externalConnection);

            final String query = "DELETE FROM recipe_steps WHERE recipe_id=?";

            try (final PreparedStatement statement = conn.prepareStatement(query)) {
                statement.setLong(1, recipeId);

                if (statement.executeUpdate() == 0) {
                    throw new IllegalArgumentException("No recipe steps found for recipe ID: " + recipeId);
                }   
            }
        } catch (SQLException e) {
            LOG.log(Level.SEVERE, "Error deleting recipe steps by recipe ID", e);
            throw new DAOException(e);
        } finally {
            closeConnection(conn, isExternalConnection);
        }
    }

    //============     AUXILIARY METHODS     ============

    /**
     * Converts a database row represented by a {@link ResultSet} into a {@link RecipeStep} entity.
     * Assumes that the ResultSet is positioned at a valid row and contains all necessary columns.
     * 
     * @param result the ResultSet containing the data of a recipe step.
     * @return a RecipeStep entity constructed from the ResultSet data.
     * @throws SQLException if there is an error accessing the ResultSet data.
     */
    private RecipeStep rowToEntity(ResultSet result)
    throws SQLException {
        Recipe recipe = new Recipe();
        recipe.setId(result.getLong("recipe_id"));

        return new RecipeStep(
            result.getLong("id_recipe_step"),
            result.getInt("step_number"),
            result.getString("title"),
            result.getString("description"),
            result.getString("image_path"),
            recipe
        );
    }

    /**
     * Validates the integrity of a {@link RecipeStep} entity before database operations.
     * Checks that the step is not null, has a valid associated recipe, a positive step number, and a non-null description.
     * 
     * @param step the recipe step to validate.
     * @throws IllegalArgumentException if the step is null or contains invalid data.
     */
    private void ensureRecipeStepDataIntegrity(RecipeStep step) throws IllegalArgumentException {
        if (step == null) {
            throw new IllegalArgumentException("Recipe step cannot be null");
        }

        if (step.getRecipe() == null || step.getRecipe().getId() <= 0) {
            throw new IllegalArgumentException("Recipe step must be associated with a valid recipe");
        }

        if (step.getStepNumber() < 1) {
            throw new IllegalArgumentException("Recipe step number must be greater than 0");
        }

        if (step.getDescription() == null || step.getDescription().trim().isEmpty()) {
            throw new IllegalArgumentException("Recipe step description cannot be null or blank");
        }

    }

}
